/* Vancouver family activity catalogue.
   Research refreshed 2026-08-13 from official attraction, municipal, and
   tourism sources. Volatile prices and opening times stay behind the source
   links; this file keeps only planning-level guidance that is useful in-app.
   2026-08-15: added a Chinatown cluster (ranks 25-29), checked fresh against
   each venue's own site. The old-style Chinatown Night Market shows up in a
   lot of search results but is not reliably operating in 2026 (Yelp lists it
   CLOSED; the one confirmed 2026 Chinatown event, the BMO Chinatown Festival,
   already happened July 25-26, before this trip) — left out rather than
   risk sending the family to a market that isn't there. */
'use strict';

window.VANCOUVER_GUIDE = Object.freeze([
  {
    id: 'vancouver-aquarium', rank: 1, icon: '🦦', name: 'Vancouver Aquarium',
    aliases: ['Vancouver Aquarium in Stanley Park'], placeQuery: 'Vancouver Aquarium Stanley Park',
    category: 'attraction', area: 'Stanley Park', duration: '2.5–3.5 hr', cost: '$$$', weather: 'indoors',
    filters: ['top', 'rain'],
    why: 'Sea otters, jellyfish, touch-friendly discovery spaces and the 4D theatre make this one of the safest big wins for age six.',
    booking: 'Book ahead for a busy or rainy day.', pair: 'Stanley Park playgrounds or the seawall',
    sourceUrl: 'https://www.vanaqua.org/visit', sourceLabel: 'Aquarium visitor info',
  },
  {
    id: 'science-world', rank: 2, icon: '🧪', name: 'Science World',
    aliases: ['Science World at TELUS World of Science'], placeQuery: 'Science World Vancouver',
    category: 'attraction', area: 'False Creek', duration: '2.5–4 hr', cost: '$$', weather: 'indoors',
    filters: ['top', 'rain'],
    why: 'Hands-on experiments, live demos and room to touch almost everything are exactly right for a curious six-year-old.',
    booking: 'Allow at least 2 hours; earlier is calmer.', pair: 'Aquabus to Granville Island',
    sourceUrl: 'https://www.scienceworld.ca/your-visit/', sourceLabel: 'Science World visitor info',
  },
  {
    id: 'stanley-park-family-loop', rank: 3, icon: '🌲', name: 'Stanley Park family loop',
    aliases: ['Stanley Park', 'Stanley Park Seawall'], placeQuery: 'Stanley Park Second Beach Vancouver',
    category: 'outdoor', area: 'Stanley Park', duration: '2–4 hr', cost: 'Free', weather: 'dry',
    filters: ['top', 'free', 'outdoor'],
    why: 'Mix a short seawall walk or bike ride with Ceperley Playground, Second Beach and forest trails instead of asking little legs to do the full loop.',
    booking: 'Choose one section, not the full 8.8 km seawall.', pair: 'Aquarium, Second Beach Pool or mini golf',
    sourceUrl: 'https://vancouver.ca/parks-recreation-culture/play-in-stanley-park.aspx', sourceLabel: 'City of Vancouver park guide',
  },
  {
    id: 'granville-island', rank: 4, icon: '🎪', name: 'Granville Island Kids Market',
    aliases: ['Kids Market', 'Granville Island'], placeQuery: 'Kids Market Granville Island Vancouver',
    category: 'attraction', area: 'Granville Island', duration: '2–3 hr', cost: '$', weather: 'mixed',
    filters: ['top', 'rain'],
    why: 'The child-sized entrance, toy shops and indoor Adventure Zone pair nicely with market snacks and watching boats outside.',
    current: '2026 note: the splash pad is temporarily closed under water restrictions; the water slide is open daily 10–6.',
    booking: 'Go near opening on a weekend.', pair: 'Aquabus and the Public Market',
    sourceUrl: 'https://kidsmarket.ca/visit/', sourceLabel: 'Kids Market visitor info',
  },
  {
    id: 'aquabus', rank: 5, icon: '⛴️', name: 'Aquabus False Creek ride',
    aliases: ['Aquabus', 'False Creek Ferries'], placeQuery: 'Aquabus Granville Island Vancouver',
    category: 'attraction', area: 'False Creek', duration: '30–90 min', cost: '$', weather: 'mixed',
    filters: ['top'],
    why: 'The tiny rainbow ferries turn transportation into an attraction, with skyline and boat views at a six-year-old-friendly pace.',
    booking: 'A day pass works well for hop-on, hop-off exploring.', pair: 'Science World, Granville Island or Vanier Park',
    sourceUrl: 'https://theaquabus.com/', sourceLabel: 'Aquabus trip planner',
  },
  {
    id: 'capilano-bridge', rank: 6, icon: '🌉', name: 'Capilano Suspension Bridge Park',
    aliases: ['Capilano Suspension Bridge'], placeQuery: 'Capilano Suspension Bridge Park North Vancouver',
    category: 'attraction', area: 'North Shore', duration: '2.5–3.5 hr', cost: '$$$', weather: 'dry',
    filters: ['top', 'outdoor'],
    why: 'The big bridge, treetop walkways and Rainforest Explorers booklet make the price easier to justify for an adventurous child.',
    booking: 'Timed entry is required; earlier usually means fewer crowds.', pair: 'Grouse Mountain only if energy is high',
    sourceUrl: 'https://www.capbridge.com/cap-kids/', sourceLabel: 'Cap Kids family guide',
  },
  {
    id: 'grouse-mountain', rank: 7, icon: '🚠', name: 'Grouse Mountain',
    aliases: ['Grouse Mountain Skyride'], placeQuery: 'Grouse Mountain North Vancouver',
    category: 'attraction', area: 'North Shore', duration: '4–6 hr', cost: '$$$', weather: 'dry',
    filters: ['top', 'outdoor'],
    why: 'The gondola is only the opener: summer admission can include grizzly bears, the lumberjack show, bird demonstrations and a kids’ canopy adventure.',
    booking: 'Check the day’s activity schedule and mountain weather first.', pair: 'Capilano Bridge for a full North Shore day',
    sourceUrl: 'https://www.grousemountain.com/current_conditions', sourceLabel: 'Grouse current activities',
  },
  {
    id: 'second-beach-pool', rank: 8, icon: '🏊', name: 'Second Beach Pool',
    aliases: ['Second Beach outdoor pool'], placeQuery: 'Second Beach Pool Stanley Park Vancouver',
    category: 'outdoor', area: 'Stanley Park', duration: '2–3 hr', cost: '$', weather: 'sunny',
    filters: ['top', 'outdoor'],
    why: 'A heated outdoor pool with gradual entry beside the beach and playground is an easy decompression block after sightseeing.',
    booking: 'Reserve the swim session; some drop-in spots exist but are not guaranteed.', pair: 'Ceperley Playground and a beach picnic',
    sourceUrl: 'https://vancouver.ca/parks-recreation-culture/second-beach-pool.aspx', sourceLabel: 'City pool schedule',
  },
  {
    id: 'playland', rank: 9, icon: '🎢', name: 'Playland',
    aliases: ['PNE Playland', 'PNE Fair'], placeQuery: 'Playland Vancouver PNE',
    category: 'attraction', area: 'Hastings Park', duration: '4–6 hr', cost: '$$$', weather: 'dry',
    filters: ['top', 'outdoor'],
    why: 'The Fun Pass includes a strong set of family rides, from the carousel and Honeybee Express to mini golf and the Westcoast Wheel.',
    current: '2026 note: regular Playland runs through Aug 21; the PNE Fair runs Aug 22–Sep 7 with different admission.',
    booking: 'Tickets are date-specific; check every ride’s height rule.', pair: 'Make this the main event of its day',
    sourceUrl: 'https://pne.ca/playland2026/', sourceLabel: 'Official 2026 dates and rides',
  },
  {
    id: 'stanley-park-mini-golf', rank: 10, icon: '⛳', name: 'Stanley Park Mini Golf',
    aliases: ['Stanley Park Mini Golf Experience'], placeQuery: 'Stanley Park Mini Golf 690 Pipeline Road Vancouver',
    category: 'attraction', area: 'Stanley Park', duration: '1–2 hr', cost: '$$', weather: 'dry',
    filters: ['outdoor'],
    why: 'This new-for-2026 course replaces the train site for the summer, with nine beginner-friendly holes before the trickier back nine.',
    current: 'The Stanley Park Train is not running; mini golf is the current attraction at the site.',
    booking: 'Choose 9 holes if the day is already busy.', pair: 'Aquarium or Lumberman’s Arch',
    sourceUrl: 'https://vancouver.ca/news-calendar/stanley-park-mini-golf-experience-opens-july-1-2026.aspx', sourceLabel: 'City 2026 announcement',
  },
  {
    id: 'bloedel', rank: 11, icon: '🦜', name: 'Bloedel Conservatory + Queen Elizabeth Park',
    aliases: ['Bloedel Conservatory', 'Queen Elizabeth Park'], placeQuery: 'Bloedel Conservatory Vancouver',
    category: 'attraction', area: 'Queen Elizabeth Park', duration: '1.5–2.5 hr', cost: '$', weather: 'mixed',
    filters: ['rain'],
    why: 'Colourful free-flying birds, koi and a warm tropical dome deliver a compact wow; the city viewpoint and gardens add a free outdoor half.',
    booking: 'A good lower-energy or drizzly-day choice.', pair: 'Queen Elizabeth Park playground and viewpoint',
    sourceUrl: 'https://vancouver.ca/parks-recreation-culture/bloedel-conservatory.aspx', sourceLabel: 'City conservatory guide',
  },
  {
    id: 'vandusen', rank: 12, icon: '🌿', name: 'VanDusen Botanical Garden hedge maze',
    aliases: ['VanDusen Botanical Garden'], placeQuery: 'VanDusen Botanical Garden Vancouver',
    category: 'outdoor', area: 'Shaughnessy', duration: '1.5–2.5 hr', cost: '$$', weather: 'dry',
    filters: ['outdoor'],
    why: 'Give the visit a mission: solve the hedge maze, spot wildlife and pick a picnic place. That lands better at six than a garden stroll.',
    booking: 'Bring a picnic for the Great Lawn.', pair: 'Bloedel Conservatory',
    sourceUrl: 'https://vancouver.ca/parks-recreation-culture/vandusen-botanical-garden.aspx', sourceLabel: 'City garden guide',
  },
  {
    id: 'flyover', rank: 13, icon: '✈️', name: 'Flyover in Vancouver',
    aliases: ['FlyOver Canada', 'Flyover Canada'], placeQuery: 'Flyover Canada Place Vancouver',
    category: 'attraction', area: 'Canada Place', duration: '45–60 min', cost: '$$$', weather: 'indoors',
    filters: ['rain'],
    why: 'A short flying-theatre ride with wind, mist and scents can feel huge without using up the whole day.',
    current: 'Every rider must be at least 102 cm (40 in) tall; skip for motion sickness or a strong fear of heights.',
    booking: 'Book a time, especially on a rainy day.', pair: 'Canada Place promenade or Vancouver Lookout',
    sourceUrl: 'https://www.experienceflyover.com/vancouver/plan-your-visit/faqs/', sourceLabel: 'Flyover visitor FAQ',
  },
  {
    id: 'space-centre', rank: 14, icon: '🚀', name: 'H.R. MacMillan Space Centre',
    aliases: ['Space Centre', 'MacMillan Space Centre'], placeQuery: 'HR MacMillan Space Centre Vancouver',
    category: 'attraction', area: 'Vanier Park', duration: '2–3 hr', cost: '$$', weather: 'indoors',
    filters: ['rain'],
    why: 'A 45-minute planetarium show, live science demo and hands-on gallery make a tidy, age-appropriate indoor package.',
    booking: 'Check show times; advance booking is not required.', pair: 'Maritime Museum or an Aquabus ride',
    sourceUrl: 'https://www.spacecentre.ca/plan-your-visit/', sourceLabel: 'Space Centre visitor info',
  },
  {
    id: 'beaty', rank: 15, icon: '🐋', name: 'Beaty Biodiversity Museum',
    aliases: ['Beaty Museum'], placeQuery: 'Beaty Biodiversity Museum UBC Vancouver',
    category: 'attraction', area: 'UBC', duration: '1.5–2.5 hr', cost: '$$', weather: 'indoors',
    filters: ['rain'],
    why: 'Canada’s largest displayed blue-whale skeleton is the hook, followed by fossils, bugs, birds and a Discovery Lab for young scientists.',
    booking: 'Check the daily schedule for tours or family activities.', pair: 'Museum of Anthropology or Pacific Spirit Park',
    sourceUrl: 'https://beatymuseum.ubc.ca/visit/', sourceLabel: 'Beaty visitor info',
  },
  {
    id: 'moa', rank: 16, icon: '🪶', name: 'Museum of Anthropology at UBC',
    aliases: ['Museum of Anthropology', 'MOA at UBC'], placeQuery: 'Museum of Anthropology at UBC Vancouver',
    category: 'attraction', area: 'UBC', duration: '1.5–2.5 hr', cost: '$$', weather: 'indoors',
    filters: ['rain'],
    why: 'Monumental carvings and Northwest Coast First Nations works can hold a child’s attention when adults turn the visit into a visual scavenger hunt.',
    booking: 'Best for an art- or story-loving six-year-old; keep the visit focused.', pair: 'Beaty Museum or a UBC beach viewpoint',
    sourceUrl: 'https://moa.ubc.ca/', sourceLabel: 'MOA visitor info',
  },
  {
    id: 'seabus-shipyards', rank: 17, icon: '🚢', name: 'SeaBus + Shipyards Splash Park',
    aliases: ['The Shipyards', 'Lonsdale Quay'], placeQuery: 'The Shipyards North Vancouver',
    category: 'outdoor', area: 'North Vancouver', duration: '2–3 hr', cost: '$', weather: 'sunny',
    filters: ['free', 'outdoor'],
    why: 'The harbour crossing feels like a boat ride, then the big waterfront splash park lets a six-year-old take over the agenda.',
    current: 'Splash park operation is weather- and water-restriction-dependent; check the City page before leaving.',
    booking: 'Pack swimwear and sandals; the splash park is free and unsupervised.', pair: 'Lonsdale Quay for lunch',
    sourceUrl: 'https://www.cnv.org/Parks-Recreation/The-Shipyards/Splash-Park', sourceLabel: 'City splash park status',
  },
  {
    id: 'maritime-museum', rank: 18, icon: '⚓', name: 'Vancouver Maritime Museum',
    aliases: ['Maritime Museum'], placeQuery: 'Vancouver Maritime Museum',
    category: 'attraction', area: 'Vanier Park', duration: '1.5–2 hr', cost: '$$', weather: 'indoors',
    filters: ['rain'],
    why: 'Ships, navigation and hands-on maritime stories work well as a smaller rainy-day museum instead of an all-day commitment.',
    current: 'The St. Roch exhibit is being revitalized for winter 2026–27; check what is open before visiting.',
    booking: 'No need to make this a full day.', pair: 'Space Centre and Vanier Park',
    sourceUrl: 'https://vanmaritime.com/', sourceLabel: 'Maritime Museum visitor info',
  },
  {
    id: 'burnaby-village', rank: 19, icon: '🎠', name: 'Burnaby Village Museum + carousel',
    aliases: ['Burnaby Village Museum'], placeQuery: 'Burnaby Village Museum',
    category: 'attraction', area: 'Burnaby', duration: '2.5–4 hr', cost: '$', weather: 'mixed',
    filters: ['free'],
    why: 'Costumed streets, old shops and a vintage carousel create a full family outing with free gate admission.',
    current: 'The museum is seasonal; carousel rides cost extra.',
    booking: 'Check that the seasonal village and carousel are open.', pair: 'Deer Lake Park',
    sourceUrl: 'https://www.burnabyvillagemuseum.ca/EN/main/visit/faqs.html', sourceLabel: 'Museum visitor FAQ',
  },
  {
    id: 'maplewood-farm', rank: 20, icon: '🐐', name: 'Maplewood Farm',
    aliases: ['Maplewood Farm North Vancouver'], placeQuery: 'Maplewood Farm North Vancouver',
    category: 'attraction', area: 'North Vancouver', duration: '1.5–2.5 hr', cost: '$', weather: 'mixed',
    filters: ['outdoor'],
    why: 'A compact working farm with goats, sheep, rabbits and family programs is a calmer alternative to another major attraction.',
    booking: 'Walk-ins are welcome; closed-toe shoes help.', pair: 'Deep Cove or the Shipyards',
    sourceUrl: 'https://maplewoodfarm.bc.ca/', sourceLabel: 'Maplewood Farm visitor info',
  },
  {
    id: 'kits-beach', rank: 21, icon: '🏖️', name: 'Kitsilano Beach + playground',
    aliases: ['Kitsilano Beach', 'Kits Beach'], placeQuery: 'Kitsilano Beach Vancouver',
    category: 'outdoor', area: 'Kitsilano', duration: '2–3 hr', cost: 'Free', weather: 'sunny',
    filters: ['free', 'outdoor'],
    why: 'Beach time, mountain views and a playground give everyone something without another ticketed attraction.',
    booking: 'Bring layers; ocean water is cold even on a warm day.', pair: 'Vanier Park museums or Granville Island',
    sourceUrl: 'https://vancouver.ca/parks-recreation-culture/beaches.aspx', sourceLabel: 'City beach guide',
  },
  {
    id: 'spanish-banks', rank: 22, icon: '🪣', name: 'Spanish Banks at low tide',
    aliases: ['Spanish Banks Beach'], placeQuery: 'Spanish Banks Beach Vancouver',
    category: 'outdoor', area: 'West Point Grey', duration: '2–3 hr', cost: 'Free', weather: 'sunny',
    filters: ['free', 'outdoor'],
    why: 'At low tide the sand seems to run forever, turning a beach stop into tide-pool poking, running and mountain watching.',
    booking: 'Check the tide table and beach water-quality notice.', pair: 'UBC museums or Pacific Spirit Park',
    sourceUrl: 'https://vancouver.ca/parks-recreation-culture/beaches.aspx', sourceLabel: 'City beach guide',
  },
  {
    id: 'lynn-canyon', rank: 23, icon: '🌲', name: 'Lynn Canyon suspension bridge',
    aliases: ['Lynn Canyon Park'], placeQuery: 'Lynn Canyon Suspension Bridge North Vancouver',
    category: 'outdoor', area: 'North Shore', duration: '2–3 hr', cost: 'Free', weather: 'dry',
    filters: ['free', 'outdoor'],
    why: 'A free suspension bridge and forest walk suit an outdoorsy child, as long as adults are ready for stairs, roots and close supervision.',
    booking: 'Arrive early; parking and the bridge get busy. Skip after heavy rain.', pair: 'Maplewood Farm',
    sourceUrl: 'https://lynncanyon.ca/', sourceLabel: 'Lynn Canyon Park guide',
  },
  {
    id: 'vancouver-lookout', rank: 24, icon: '🌆', name: 'Vancouver Lookout',
    aliases: ['Vancouver Lookout at Harbour Centre'], placeQuery: 'Vancouver Lookout Harbour Centre',
    category: 'attraction', area: 'Downtown', duration: '45–60 min', cost: '$$', weather: 'indoors',
    filters: ['rain'],
    why: 'The glass elevator and 360-degree view are a short, low-effort way to help a child understand the city you have been exploring.',
    booking: 'Aim for a clear day; advance tickets are recommended.', pair: 'Gastown Steam Clock or Canada Place',
    sourceUrl: 'https://vancouverlookout.com/know-before-you-go', sourceLabel: 'Lookout visitor info',
  },
  {
    id: 'sun-yat-sen-garden', rank: 25, icon: '🎋', name: 'Dr. Sun Yat-Sen Classical Chinese Garden',
    aliases: ['Sun Yat-Sen Classical Chinese Garden', 'Chinese Garden'], placeQuery: 'Dr. Sun Yat-Sen Classical Chinese Garden Vancouver',
    category: 'attraction', area: 'Chinatown', duration: '1–1.5 hr', cost: '$$', weather: 'mixed',
    filters: ['top'],
    why: 'The first full-scale Ming-dynasty-style garden built outside China — koi and turtles in the pond, covered walkways and moon-gate doorways give a six-year-old plenty to spot on a guided tour.',
    current: 'Closed Mondays; children under 6 are free but Lily (6) needs a ticket — the two-adult/up-to-three-kids family rate is the better deal.',
    booking: 'A free 45-minute guided tour runs most days — worth timing the visit around it.', pair: 'Sun Yat-Sen Park next door, or the Chinatown Storytelling Centre',
    sourceUrl: 'https://vancouverchinesegarden.com/visit/', sourceLabel: 'Garden visitor info',
  },
  {
    id: 'sun-yat-sen-park', rank: 26, icon: '🪷', name: 'Sun Yat-Sen Park',
    aliases: ['Dr. Sun Yat-Sen Park'], placeQuery: 'Dr. Sun Yat-Sen Park Vancouver Chinatown',
    category: 'outdoor', area: 'Chinatown', duration: '20–30 min', cost: 'Free', weather: 'mixed',
    filters: ['free', 'outdoor'],
    why: 'The free public half of the same pond and garden grounds — enough lotus flowers, koi and a pavilion to enjoy without paying for or queuing at the ticketed garden.',
    booking: 'A relaxed 20-minute stop; pairs naturally either side of the ticketed garden.', pair: 'Dr. Sun Yat-Sen Classical Chinese Garden',
    sourceUrl: 'https://covapp.vancouver.ca/ParkFinder/parkdetail.aspx?inparkid=30', sourceLabel: 'City park page',
  },
  {
    id: 'chinatown-storytelling-centre', rank: 27, icon: '📞', name: 'Chinatown Storytelling Centre',
    aliases: ['Storytelling Centre'], placeQuery: 'Chinatown Storytelling Centre Vancouver',
    category: 'attraction', area: 'Chinatown', duration: '45–75 min', cost: '$', weather: 'indoors',
    filters: ['top', 'rain'],
    why: 'Built for hands-on exploring rather than reading walls of text: a pagoda phone booth of recorded stories, a dress-up photo studio and a projected banquet-table game a six-year-old can actually play.',
    current: 'Open Friday to Sunday only (closed Mon-Thu) — of this trip’s Vancouver days (17 Mon - 21 Fri), only Friday the 21st works.',
    booking: 'Children 11 and under are free with a ticketed adult.', pair: 'Chinese Canadian Museum or the Millennium Gate walk',
    sourceUrl: 'https://www.chinatownstorytellingcentre.org/visit/', sourceLabel: 'Storytelling Centre visitor info',
  },
  {
    id: 'chinese-canadian-museum', rank: 28, icon: '🏮', name: 'Chinese Canadian Museum',
    aliases: ['Chinese Canadian Museum at the Wing Sang Building', 'Wing Sang Building'], placeQuery: 'Chinese Canadian Museum Vancouver Wing Sang Building',
    category: 'attraction', area: 'Chinatown', duration: '45–75 min', cost: '$', weather: 'indoors',
    filters: ['rain'],
    why: 'Vancouver’s oldest Chinatown building (1889), with real family history behind it — leans more look-and-listen than hands-on, so it suits a calmer stretch of the day rather than the main event.',
    current: 'Open Wed-Sun plus holiday Mondays (closed Mon-Tue otherwise) — of this trip’s Vancouver days (17 Mon - 21 Fri), Wed 19 through Fri 21 work; Mon 17 and Tue 18 do not.',
    booking: 'Pair with the more interactive Storytelling Centre so the museum stretch stays short.', pair: 'Chinatown Storytelling Centre',
    sourceUrl: 'https://www.chinesecanadianmuseum.ca/plan-your-visit/', sourceLabel: 'Museum visitor info',
  },
  {
    id: 'chinatown-gate-walk', rank: 29, icon: '🀄', name: 'Millennium Gate + Sam Kee Building walk',
    aliases: ['Chinatown Millennium Gate', 'Sam Kee Building', "World's Narrowest Building"], placeQuery: 'Chinatown Millennium Gate Vancouver',
    category: 'outdoor', area: 'Chinatown', duration: '20–30 min', cost: 'Free', weather: 'mixed',
    filters: ['top', 'free', 'outdoor'],
    why: 'Give it a mission instead of a stroll: find the stone lions guarding the big dragon-topped gate, then walk one block to the Sam Kee Building — a real Guinness World Record for narrowest building, under 5 feet wide.',
    booking: 'A quick 20-minute add-on before or after anything else in Chinatown, any day, any weather.', pair: 'Any of the other Chinatown stops',
    sourceUrl: 'https://vancouver.ca/parks-recreation-culture/chinatown-architectural-walk.aspx', sourceLabel: 'City architectural walk guide',
  },
]);
